# Generated by Django 5.1.1 on 2024-10-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_collections_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='feature_product',
            new_name='featured_product',
        ),
    ]
