# Generated by Django 5.1.1 on 2024-10-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_feature_product_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place_at',
            new_name='placed_at',
        ),
    ]
