# Generated by Django 5.1.3 on 2024-12-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
